name: Deploy

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Clone API submodule'
        env:
          REPO_KEY: ${{ secrets.API_REPOSITORY_KEY }}
        run: |
          echo "$REPO_KEY" > repo.key && chmod 400 repo.key
          export GIT_SSH_COMMAND="ssh -i repo.key"
          git submodule update --init
          rm repo.key

      - name: 'Setup node'
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: 'Deploy to Vercel'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          prodDeployArg=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodDeployArg="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodDeployArg
